name: Tests Magic Ape Subgraph

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      with:
          version: 8

    - name: install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Codegen subgraphs
      run: NETWORK=ethereum pnpm exec turbo run build --scope=magic-ape --force
    
    - name: Run the tests
      run: pnpm exec turbo run test --scope=magic-ape